packages:
  - packages/*
  - docs

catalog:
  'svelte': '^5.19.7'
  'svelte-check': '^4.1.4'
  'tslib': '^2.8.1'
  'typescript': '^5.4.5'
  'vite': '^6.1.0'
  '@sveltejs/adapter-auto': '^4.0.0'
  '@sveltejs/adapter-static': '^3.0.8'
  '@sveltejs/kit': '^2.17.1'
  '@sveltejs/vite-plugin-svelte': '5.0.3'
  '@sveltejs/package': '^2.3.10'
  '@types/node-emoji': '^1.8.2'
