export { default as CartaEditor } from '$lib/CartaEditor.svelte';
export { default as CartaViewer } from '$lib/CartaViewer.svelte';
export type { CartaInput, TextSelection } from '$lib/internal/input';
export type { CartaIcon } from '$lib/internal/icons';
export type { KeyboardShortcut } from '$lib/internal/shortcuts';
export type { Prefix } from '$lib/internal/prefixes';
export * from '$lib/internal/carta';
export * from '$lib/internal/highlight';
export * from '$lib/internal/textarea-props';
export * from './default.css?inline';
export * from './light.css?inline';
